# Generated by Django 5.0.7 on 2024-08-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True),
        ),
    ]
