# Generated by Django 5.0.9 on 2024-11-14 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_questiontopicnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontopicnotification',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_topics', to='bot.page', verbose_name='Отношение к странице'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_questions', to='bot.page', verbose_name='Отношение к странице'),
        ),
    ]
