# Generated by Django 5.0.7 on 2024-08-18 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='bot.page', verbose_name='Отношение к странице'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='bot.category', verbose_name='Категория'),
        ),
    ]
